# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfsconfig', models.CharField(max_length=500)),
                ('topology', models.CharField(max_length=50)),
                ('idchain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ide.Chain')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfs', models.CharField(max_length=500)),
                ('ip', models.CharField(max_length=50)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
    ]
