# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0002_configuration_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='url',
            field=models.CharField(default='http://localhost:8080', max_length=200),
            preserve_default=False,
        ),
    ]
